package socket

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type RealmAdapterOptions struct {
	ConfigPath       string
	RunCheckAndApply func(configPath string) error
}

type realmAdapter struct {
	opts RealmAdapterOptions
}

func NewRealmAdapter(opts RealmAdapterOptions) ForwardEngine {
	if strings.TrimSpace(opts.ConfigPath) == "" {
		opts.ConfigPath = "/etc/realm/realm.toml"
	}
	if opts.RunCheckAndApply == nil {
		opts.RunCheckAndApply = func(configPath string) error {
			if _, err := exec.LookPath("realm"); err != nil {
				// Skip runtime check if realm binary is absent in current node.
				return nil
			}
			return exec.Command("realm", "-c", configPath).Run()
		}
	}
	return &realmAdapter{opts: opts}
}

func (r *realmAdapter) Name() string {
	return "realm"
}

func (r *realmAdapter) DryRun(_ context.Context, req ForwardApplyRequest) (*ForwardApplyResult, error) {
	if err := validateForwardRules(req.Forwards); err != nil {
		return nil, err
	}
	if _, err := r.renderRealmConfig(req.Forwards); err != nil {
		return nil, err
	}
	return &ForwardApplyResult{
		Engine:       r.Name(),
		RulesApplied: len(req.Forwards),
		Message:      "dry-run passed",
	}, nil
}

func (r *realmAdapter) Apply(_ context.Context, req ForwardApplyRequest) (*ForwardApplyResult, error) {
	if err := validateForwardRules(req.Forwards); err != nil {
		return nil, err
	}
	content, err := r.renderRealmConfig(req.Forwards)
	if err != nil {
		return nil, err
	}

	prev, existed, err := readFileIfExists(r.opts.ConfigPath)
	if err != nil {
		return nil, fmt.Errorf("read realm config backup failed: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(r.opts.ConfigPath), 0755); err != nil {
		return nil, fmt.Errorf("prepare realm config dir failed: %w", err)
	}
	if err := os.WriteFile(r.opts.ConfigPath, []byte(content), 0644); err != nil {
		return nil, fmt.Errorf("write realm config failed: %w", err)
	}
	if err := r.opts.RunCheckAndApply(r.opts.ConfigPath); err != nil {
		_ = restoreFile(r.opts.ConfigPath, prev, existed, 0644)
		return nil, fmt.Errorf("apply realm config failed: %w", err)
	}

	return &ForwardApplyResult{
		Engine:       r.Name(),
		RulesApplied: len(req.Forwards),
		Message:      "apply succeeded",
	}, nil
}

func (r *realmAdapter) renderRealmConfig(forwards []ForwardPortRule) (string, error) {
	var b strings.Builder
	b.WriteString("# generated by Fork-Nft realm adapter\n")
	for _, f := range forwards {
		target := strings.TrimSpace(f.Target)
		if target == "" {
			return "", fmt.Errorf("target is required")
		}
		b.WriteString("\n[[endpoints]]\n")
		b.WriteString(fmt.Sprintf("listen = \"0.0.0.0:%d\"\n", f.RelayPort))
		b.WriteString(fmt.Sprintf("remote = \"%s:%d\"\n", target, f.TargetPort))
		if strings.EqualFold(strings.TrimSpace(f.Protocol), "udp") {
			b.WriteString("transport = \"udp\"\n")
		} else {
			b.WriteString("transport = \"tcp\"\n")
		}
	}
	return b.String(), nil
}
